### ISSUE TITLE
7zip download link broken

### ISSUE THREAD

**Issue by pctutorialsonline** [That-Dude/rc-backup#1]
Hi there,

It seems the location/version of 7zip has changed. Currently returning a 404. The updated link should be: https://7-zip.org/a/7z2201-linux-x64.tar.xz

John

**Comment by That-Dude** [comment]
Hi John

Thanks so much for taking the time to open an issue request. I've updated the 7zip link.

Dan

**Comment by pctutorialsonline** [comment]
Thanks Dan. Brilliant script! Many thanks for sharing.
